"""added is_active_project and is_deactivated_project fields

Revision ID: 279bca80e20b
Revises: 6949b64768df
Create Date: 2024-01-20 10:27:54.464995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279bca80e20b'
down_revision: Union[str, None] = '6949b64768df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_activated_project', sa.Boolean(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('is_deactivated_project', sa.Boolean(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_deactivated_project')
        batch_op.drop_column('is_activated_project')

    # ### end Alembic commands ###
