"""delete redundant person_uniqueid

Revision ID: 27f656f0ac00
Revises: 7651071cd30e
Create Date: 2023-09-07 18:20:16.543735

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '27f656f0ac00'
down_revision: Union[str, None] = '7651071cd30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('person_uniqueid')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_uniqueid', sa.VARCHAR(length=60), server_default='', nullable=False))

    # ### end Alembic commands ###
