"""added person_type field

Revision ID: 33e86c0fde3b
Revises: bd754fd260ed
Create Date: 2024-06-09 23:04:15.005746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e86c0fde3b'
down_revision: Union[str, None] = 'bd754fd260ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_type', sa.String(length=32), nullable=False, server_default='local'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('person_type')

    # ### end Alembic commands ###
