"""remove person_oib field

Revision ID: 3eaf5dccc6b4
Revises: 5424372ed0c7
Create Date: 2024-02-23 17:54:54.705198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eaf5dccc6b4'
down_revision: Union[str, None] = '5424372ed0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('person_oib')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_oib', sa.VARCHAR(length=11), nullable=False))

    # ### end Alembic commands ###
