"""remove slipped mail_project_sshkey field

Revision ID: 4ecf67c4b990
Revises: 899730d36e9b
Create Date: 2023-12-10 14:18:07.772681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4ecf67c4b990'
down_revision: Union[str, None] = '899730d36e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mail_project_sshkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_project_sshkey', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###
