"""added type_create field

Revision ID: 4f28e6e80197
Revises: 1b04100c64f1
Create Date: 2023-10-05 17:35:07.819883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f28e6e80197'
down_revision: Union[str, None] = '1b04100c64f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_create', sa.String(length=10), nullable=False, server_default=''))
    op.execute('UPDATE users SET type_create="api"')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('type_create')

    # ### end Alembic commands ###
