"""add new fields related to SSH key delete reporting

Revision ID: 5424372ed0c7
Revises: 421b74b19d9c
Create Date: 2024-02-05 13:25:55.333160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5424372ed0c7'
down_revision: Union[str, None] = '421b74b19d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_is_sshkeyremoved', sa.Boolean(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('mail_project_is_sshkeyremoved', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mail_project_is_sshkeyremoved')
        batch_op.drop_column('mail_is_sshkeyremoved')

    # ### end Alembic commands ###
