"""remove mail_is_subscribed

Revision ID: 6949b64768df
Revises: f9637001882f
Create Date: 2024-01-18 16:50:59.568549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6949b64768df'
down_revision: Union[str, None] = 'f9637001882f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mail_is_subscribed')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_is_subscribed', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
