"""added mail_project mapping fields

Revision ID: 899730d36e9b
Revises: 4f28e6e80197
Create Date: 2023-12-10 13:47:24.247133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899730d36e9b'
down_revision: Union[str, None] = '4f28e6e80197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
