"""add skip_defgid field

Revision ID: bd754fd260ed
Revises: 3eaf5dccc6b4
Create Date: 2024-03-14 19:25:09.114180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd754fd260ed'
down_revision: Union[str, None] = '3eaf5dccc6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_defgid', sa.Boolean(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('skip_defgid')

    # ### end Alembic commands ###
