"""added mail_project_* mapping flag fields

Revision ID: d0dccfda2b05
Revises: 4f28e6e80197
Create Date: 2023-12-10 23:58:56.897887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0dccfda2b05'
down_revision: Union[str, None] = '4f28e6e80197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_project_is_opensend', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('mail_project_is_sshkeyadded', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mail_project_is_sshkeyadded')
        batch_op.drop_column('mail_project_is_opensend')

    # ### end Alembic commands ###
