"""added mail_is_deactivated and mail_is_activated fields

Revision ID: f9637001882f
Revises: d0dccfda2b05
Create Date: 2024-01-16 21:11:37.444175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9637001882f'
down_revision: Union[str, None] = 'd0dccfda2b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_is_activated', sa.Boolean(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('mail_is_deactivated', sa.Boolean(), nullable=False, server_default=''))
    op.execute('UPDATE users SET mail_is_activated=0')
    op.execute('UPDATE users SET mail_is_deactivated=0')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mail_is_deactivated')
        batch_op.drop_column('mail_is_activated')

    # ### end Alembic commands ###
