"""add boolean fields on user and rename field o project model

Revision ID: fb8517e8ee1a
Revises: 27f656f0ac00
Create Date: 2023-09-07 18:48:20.095844

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fb8517e8ee1a'
down_revision: Union[str, None] = '27f656f0ac00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resources_type', sa.JSON(), nullable=False, server_default=''))
        batch_op.drop_column('staff_resource_type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_staff')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_resource_type', sqlite.JSON(), nullable=False))
        batch_op.drop_column('resources_type')

    # ### end Alembic commands ###
