"""rename it as person_uniqueid

Revision ID: fb9aa043b195
Revises: 970ac9410073
Create Date: 2023-09-08 14:32:43.299660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9aa043b195'
down_revision: Union[str, None] = '970ac9410073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_uniqueid', sa.String(length=128), nullable=False))
        batch_op.drop_column('person_unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_unique', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('person_uniqueid')

    # ### end Alembic commands ###
